#!/usr/bin/perl -I/usr/share/freemed/lib/perl
# $Id$
#
# Authors:
#      Jeff Buchbinder <jeff@freemedsoftware.org>
#
# FreeMED Electronic Medical Record and Practice Management System
# Copyright (C) 1999-2007 FreeMED Software Foundation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# Add proper libraries for XML-RPC access and configuration data
use Frontier::Client;
use Config::IniFiles;

# First, we get the name of the tiff image
my $original = shift || 'test.djvu';
print "Fax Import ------\n";
print "original file name = $original\n";

# Get link information from the configuration file. In future, this should
# probably be generated by the FreeMED install wizard as a special XML-RPC
# account, so internal processes can use the same configuration file.
my $config = new Config::IniFiles ( -file => '/usr/share/freemed/data/config/xmlrpc.ini' );

# Store the name of the fax file
my $document = $original;
my $local_filename = `basename "$document"`;
$local_filename =~ s/\n//g;
my $path = $config->val('freemed', 'path'); 
print "document = $document, local filename = $local_filename, path = $path\n";

# Attach via XML-RPC Lite package, using fax import method
my $client = Frontier::Client->new (
	url => $config->val('freemed', 'url'),
	username => $config->val('freemed', 'username'),
	password => $config->val('freemed', 'password'),
	debug => $config->val('freemed', 'debug')
);
print "calling FreeMED.Fax.AddLocalFile\n";
my $result = $client->call('FreeMED.Fax.AddLocalFile', $local_filename);
print "result = "; print($result); print "\n";

# Move document into incoming faxes directory
print "moving document into unfiled faxes\n";
`mv "$document" "$path/data/fax/unfiled/" -f`;

# Update permissions for web user
my $webuser = $config->val('freemed', 'webuser');
print "updating permissions to $webuser\n";
`chown $webuser.$webuser "$path/data/fax/unfiled/$local_filename"`;

# Remove *original* document (tiff)
print "removing original\n";
unlink($original);
#`mv $original /root/keep-fax/`;

